In [12]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
import sklearn

In [10]:
address_1='/Users/Arnav Singh/Desktop\Arnav/Summer Analytics/SA_Train_Data.csv'
address_2='/Users/Arnav Singh/Desktop/Arnav/Summer Analytics/SA_Test_Data.csv'
Advertisement_Train=pd.read_csv(address_1)
Advertisement_Test=pd.read_csv(address_2)
Advertisement_Train.head(1000)

FileNotFoundError: ignored

In [11]:
cols_with_missing = [col for col in Advertisement_Train.columns if Advertisement_Train[col].isnull().any()]
Advertisement_Train.drop(cols_with_missing, axis=1, inplace=True)
Advertisement_Test.drop(cols_with_missing, axis=1, inplace=True)
Advertisement_Train.drop(['date','campaign'], axis=1 ,inplace=True)
Advertisement_Test.drop(['date','campaign'], axis=1 ,inplace=True)
Advertisement_Train.head(15)

NameError: ignored

In [ ]:
from sklearn.model_selection import train_test_split
y=Advertisement_Train.revenue
features=['adgroup','ad','impressions','clicks','cost','conversions']
X=Advertisement_Train[features]
X_train,X_valid,y_train,y_valid= train_test_split(X, y,train_size=0.8, test_size=0.2, random_state=0)
X_test = Advertisement_Test[features]

In [ ]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import mean_absolute_error
from sklearn.impute import SimpleImputer
def score_dataset(X_train, X_valid, y_train, y_valid):
    RandomForestModel = RandomForestRegressor(n_estimators=10000, random_state=0)
    RandomForestModel.fit(X_train, y_train)
    Predictions = RandomForestModel.predict(X_valid)
    return mean_absolute_error(y_valid, Predictions)

In [ ]:
drop_X = X.select_dtypes(exclude=['object'])
drop_X_test = X_test.select_dtypes(exclude=['object'])
RandomForestModel = XGBRegressor(n_estimators=1000, learning_rate=0.05)
RandomForestModel.fit(drop_X,y)
predictions=RandomForestModel.predict(drop_X_test)
print(predictions)
revenue_prediction =pd.DataFrame(predictions)
revenue_prediction.columns = ["revenue"]
revenue_prediction.to_csv('RevenuePredictions12.csv',index=False)

[ 1.20417015e+02  1.30619264e+00  9.71827358e-02  9.71827358e-02
  9.71827358e-02  9.71827358e-02  1.11472130e+02  9.71827358e-02
  2.09832504e+02  1.36097848e-01  2.46274078e+02  9.20420811e-02
 -2.93666720e-01  2.95582153e+02  9.71827358e-02  1.12195160e+02
  2.81126285e+00  1.79420990e+02 -1.02712154e+00  1.52732071e+02
  9.71827358e-02 -6.81874704e+00  9.71827358e-02  3.64871185e+02
  9.71827358e-02  9.71827358e-02  4.37804260e+02  1.99503952e+02
  9.71827358e-02  9.71827358e-02  4.58393219e+02  1.84747919e-01
  6.96779297e+02  3.34910492e+02  1.39367905e+02  9.71827358e-02
  6.79681396e+01 -6.65493250e-01  9.71827358e-02  1.08450517e-01
  2.31007591e-01 -3.54387164e+00  9.71827358e-02 -2.02119684e+00
  7.85614443e+00  9.71827358e-02  9.71827358e-02  9.71827358e-02
 -1.56288028e-01 -2.68954039e-01  9.71827358e-02  1.27868444e-01
  6.50631428e+00  3.09536804e+02  1.56389664e+02  1.66288788e+02
  9.71827358e-02  9.71827358e-02  9.71827358e-02  7.72707581e+02
  9.71827358e-02  2.59970032e+02  9.71827358e-02  3.44616730e+02
  9.71827358e-02 -1.24786615e+00  2.56801483e+02  2.58986786e+02
  9.71827358e-02  9.71827358e-02  2.79154358e+02  9.71827358e-02
  9.71827358e-02  9.71827358e-02  7.85084839e+01  2.39520966e+02
  5.07106995e+02  9.71827358e-02 -4.60558558e+00  1.56434670e-01
  2.27551041e+02  2.32859222e+02 -2.63783813e+00  1.05910027e+02
  1.20631285e-01  9.71827358e-02  5.52673828e+02  1.23958496e+03
  9.71827358e-02  5.17705811e+02  3.43077820e+02  3.53059448e+02
 -4.86082649e+00  6.03431824e+02  1.14609192e+02  9.71827358e-02
  9.71827358e-02  9.71827358e-02  5.12939301e+01  9.71827358e-02
  1.27327278e+02  9.71827358e-02  9.71827358e-02  2.54745941e+02
  9.71827358e-02  1.81293359e+03  9.71827358e-02  3.13470306e+02
  9.71827358e-02  1.55503113e+02  9.71827358e-02  1.00705237e+03
  2.47046202e-01  3.10084167e+02  2.47046202e-01  1.75494873e+03
 -7.48237520e-02  2.02086646e+03  5.41460999e+02  1.52254486e+02
  9.71827358e-02  9.71827358e-02  3.72575928e+02  9.71827358e-02
 -4.11700867e-02  9.71827358e-02  5.51816406e+02  9.71827358e-02
  2.11339005e+02  1.75033112e+02  9.71827358e-02  9.71827358e-02
  2.47046202e-01  1.62007138e-01  5.50964722e+02  1.24286655e-02
 -1.46351242e+00  1.56434670e-01  4.47225372e+02  9.71827358e-02
  2.20616150e+02  9.71827358e-02 -2.93666720e-01  9.71827358e-02
  1.29943390e+02  9.71827358e-02  9.71827358e-02  1.97471069e+02
  4.01225739e+02 -8.46669972e-02  9.71827358e-02  9.71827358e-02
  6.30053040e+02  9.71827358e-02  1.87652237e+02  9.71827358e-02
  6.40211426e+02  9.71827358e-02 -5.28617561e-01  1.62007138e-01
  8.40699081e+01  9.71827358e-02 -4.32141495e+00  1.09255701e-01
  1.80626862e+02  9.71827358e-02  2.51172073e+02 -1.32056022e+00
  9.71827358e-02 -5.53127229e-01  1.62007138e-01  9.71827358e-02
 -3.17835808e+00  1.94184464e+02  9.71827358e-02 -3.37163627e-01
  9.71827358e-02  9.71827358e-02  1.91527985e+02  1.31121429e+02
  9.71827358e-02 -2.08853130e+01  9.71827358e-02  1.48782745e+02
 -1.18084645e+00 -2.22278810e+00  2.92427704e+02  7.31848373e+01
  9.85434799e+01  9.71827358e-02  7.99169846e+01  1.05267860e+02
 -4.86082649e+00 -3.37163627e-01  1.37859711e+02  1.31495297e-01
  9.71827358e-02  9.71827358e-02 -5.28617561e-01  2.02083893e+02
  2.62952118e+02  9.71827358e-02  1.85952866e+02  9.71827358e-02
  9.71827358e-02  1.07463872e+00  1.09242279e+02 -5.53127229e-01
  9.01972950e-01  3.48281128e+02  9.71827358e-02 -1.31633365e+00
 -1.35769296e+00  1.16226891e+02  3.58828979e+02  9.71827358e-02
  3.04157305e+00 -7.48237520e-02 -2.68954039e-01  5.67197144e+02
  9.71827358e-02 -3.37163627e-01  6.26151657e+00  9.71827358e-02
  9.71827358e-02  4.77511200e+02  9.71827358e-02  9.71827358e-02
  2.05806446e+01  9.71827358e-02  3.36659180e+02 -7.01349318e-01
 -1.44266295e+00  4.22820330e+00 -3.40030603e-02  3.61654282e-01
  9.71827358e-02  1.11303383e+02 -3.35615605e-01  2.62690187e+00
  9.71827358e-02  9.71827358e-02 -9.74441707e-01 -2.93666720e-01
  9.71827358e-02  1.60464081e+02  9.71827358e-02 -3.56562018e+00
  9.71827358e-02  9.71827358e-02  5.67658447e+02  1.45236755e+02
  9.71827358e-02  3.96073700e+02  9.71827358e-02  6.63607864e+01
 -8.79740953e-01  2.87036967e+00  1.19942352e+02  9.77218018e+01
  9.71827358e-02  2.45900894e+02 -3.85882926e+00  4.20503693e+01
  9.71827358e-02 -5.28617561e-01 -2.85274553e+00  9.71827358e-02
  9.71827358e-02  9.71827358e-02  3.29783264e+02  9.71827358e-02
 -2.93666720e-01  5.40562195e+02  9.71827358e-02  9.71827358e-02
  9.71827358e-02  2.16728912e+02  1.14627846e+02  9.71827358e-02
 -2.22786099e-01  4.03887212e-01  6.07626438e+00  9.71827358e-02
  2.65923340e+02  5.61969697e-01  1.20106117e+02 -2.56554484e+00
  9.71827358e-02  1.27615213e-01  2.47046202e-01  2.03316223e+02
  8.70919108e-01  9.71827358e-02  1.98109299e+02 -2.68954039e-01
  9.71827358e-02  1.87755035e+02  9.71827358e-02  9.71827358e-02
  9.71827358e-02  9.71827358e-02  5.07226013e+02 -1.10943689e+01
  2.55849749e-01 -7.54218519e-01  5.63488770e+02 -2.03437269e-01
  9.71827358e-02  2.53837570e+02  9.07742691e+01  8.52710342e+01
  9.71827358e-02  9.71827358e-02  9.71827358e-02  3.45227867e-01
  9.71827358e-02  2.35951538e+02]

In [ ]:
drop_X_train = X_train.select_dtypes(exclude=['object'])
drop_X_valid = X_valid.select_dtypes(exclude=['object'])
drop_X_test = X_test.select_dtypes(exclude=['object'])
drop_X_train['CTR']=drop_X_train['clicks']/drop_X_train['impressions']
drop_X_train['CPC']=drop_X_train['cost']/drop_X_train['clicks']
drop_X_train['CPA']=drop_X_train['cost']/drop_X_train['conversions']
drop_X_valid['CTR']=drop_X_valid['clicks']/drop_X_valid['impressions']
drop_X_valid['CPC']=drop_X_valid['cost']/drop_X_valid['clicks']
drop_X_valid['CPA']=drop_X_valid['cost']/drop_X_valid['conversions']
drop_X_test['CTR']=drop_X_test['clicks']/drop_X_test['impressions']
drop_X_test['CPC']=drop_X_test['cost']/drop_X_test['clicks']
drop_X_test['CPA']=drop_X_test['cost']/drop_X_test['conversions']
drop_X_train.head(25)

<ipython-input-126-c0b7a7ea1d9c>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  drop_X_train['CTR']=drop_X_train['clicks']/drop_X_train['impressions']
<ipython-input-126-c0b7a7ea1d9c>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  drop_X_valid['CTR']=drop_X_valid['clicks']/drop_X_valid['impressions']
<ipython-input-126-c0b7a7ea1d9c>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  drop_X_test['CTR']=drop_X_test['clicks']/drop_X_test['impressions']

      impressions  clicks   cost  conversions       CTR       CPC        CPA
483           398     188  62.03            7  0.472362  0.329947   8.861429
982           442     212  57.45            1  0.479638  0.270991  57.450000
4101           16       7   0.07            0  0.437500  0.010000        inf
2829           39      17   0.21            0  0.435897  0.012353        inf
2627            9       6   0.07            0  0.666667  0.011667        inf
1746          315     147  19.25            4  0.466667  0.130952   4.812500
1513           21       7   1.29            0  0.333333  0.184286        inf
1953           15       8   1.30            0  0.533333  0.162500        inf
2518            1       0   0.00            0  0.000000       NaN        NaN
3112            8       5   0.10            1  0.625000  0.020000   0.100000
2231           67      39   0.61            2  0.582090  0.015641   0.305000
3582           16       8   1.51            0  0.500000  0.188750        inf
4093           18      10   0.11            1  0.555556  0.011000   0.110000
841             2       3   0.09            0  1.500000  0.030000        inf
2254           19      10   0.79            2  0.526316  0.079000   0.395000
2891            1       1   0.02            0  1.000000  0.020000        inf
1259          351     171   8.35            1  0.487179  0.048830   8.350000
3008           11       2   0.02            0  0.181818  0.010000        inf
2992          147      63   0.84            1  0.428571  0.013333   0.840000
971             4       1   0.01            0  0.250000  0.010000        inf
3473            3       1   0.01            0  0.333333  0.010000        inf
3256           12       8   0.10            0  0.666667  0.012500        inf
871            10       4   0.05            0  0.400000  0.012500        inf
843            86      41   0.45            0  0.476744  0.010976        inf
3970           19      10   0.16            0  0.526316  0.016000        inf

In [ ]:
drop_X_train = drop_X_train.replace([np.inf, -np.inf], np.nan)
drop_X_valid = drop_X_valid.replace([np.inf, -np.inf], np.nan)
drop_X_test = drop_X_test.replace([np.inf, -np.inf], np.nan)

In [ ]:
drop_X_train.drop(['clicks'], axis=1 ,inplace=True)
drop_X_train.head()

      impressions   cost  conversions       CTR       CPC        CPA
483           398  62.03            7  0.472362  0.329947   8.861429
982           442  57.45            1  0.479638  0.270991  57.450000
4101           16   0.07            0  0.437500  0.010000        NaN
2829           39   0.21            0  0.435897  0.012353        NaN
2627            9   0.07            0  0.666667  0.011667        NaN

In [ ]:
drop_X_valid.drop(['clicks'], axis=1 ,inplace=True)
drop_X_valid.head()

/Users/Arnav/opt/anaconda3/lib/python3.8/site-packages/ipykernel/ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

      impressions  cost  conversions       CTR       CPC    CPA
773             9  0.03            0  0.333333  0.010000    NaN
2507          233  1.95            0  0.416309  0.020103    NaN
4198          250  2.02            4  0.352000  0.022955  0.505
1596           11  1.75            0  0.727273  0.218750    NaN
3241           29  0.12            0  0.413793  0.010000    NaN

In [ ]:
drop_X_test.drop(['clicks'], axis=1 ,inplace=True)
drop_X_test.head()

/Users/Arnav/opt/anaconda3/lib/python3.8/site-packages/ipykernel/ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

   impressions  cost  conversions       CTR       CPC   CPA
0          121  0.58            1  0.404959  0.011837  0.58
1           22  0.17            0  0.545455  0.014167   NaN
2            5  0.05            0  0.600000  0.016667   NaN
3            2  0.01            0  0.500000  0.010000   NaN
4            3  0.01            0  0.333333  0.010000   NaN

In [ ]:
# Imputation
my_imputer = SimpleImputer()
imputed_X_train = pd.DataFrame(my_imputer.fit_transform(drop_X_train))
imputed_X_valid = pd.DataFrame(my_imputer.transform(drop_X_valid))
imputed_X_test = pd.DataFrame(my_imputer.transform(drop_X_test))

# Imputation removed column names; put them back
imputed_X_train.columns = drop_X_train.columns
imputed_X_valid.columns = drop_X_valid.columns
imputed_X_test.columns = drop_X_test.columns
print(score_dataset(imputed_X_train, imputed_X_valid, y_train, y_valid))

In [ ]:
RandomForestModel = XGBRegressor(n_estimators=1000, random_state=0)
RandomForestModel.fit(imputed_X_train, y_train)
Predictions10 = RandomForestModel.predict(imputed_X_test)
print(Predictions10)

In [ ]:
revenue_prediction =pd.DataFrame(Predictions10)
revenue_prediction.columns = ["revenue"]
revenue_prediction.to_csv('RevenuePredictions12.csv',index=False)

In [ ]:
from hyperopt import fmin, tpe, rand, hp, Trials, STATUS_OK
import xgboost
from xgboost import XGBRegressor
from sklearn.model_selection import cross_val_score
import mlflow

In [ ]:
def train(params):
        """
        An example train method that computes the square of the input.
        This method will be passed to `hyperopt.fmin()`.
        
        :param params: hyperparameters. Its structure is consistent with how search space is defined. See below.
        :return: dict with fields 'loss' (scalar loss) and 'status' (success/failure status of run)
        """
        curr_model =  XGBRegressor(learning_rate=params[0],
                                gamma=int(params[1]),
                                max_depth=int(params[2]),
                                n_estimators=int(params[3]),
                                min_child_weight = params[4], objective='reg:squarederror')
        score = -cross_val_score(curr_model, X_train, y_train, scoring='neg_mean_squared_error').mean()
        score = np.array(score)
        
        return {'loss': score, 'status': STATUS_OK, 'model': curr_model}
    
    
    # define search parameters and whether discrete or continuous
search_space = [ hp.uniform('learning_rate', 0, 1),
                        hp.uniform('gamma', 0, 5),
                        hp.randint('max_depth', 10),
                        hp.randint('n_estimators', 20),
                        hp.randint('min_child_weight', 10)
                    ]
    # define the search algorithm (TPE or Randomized Search)
    algo= tpe.suggest
    
from hyperopt import SparkTrials
search_parallelism = 4
spark_trials = SparkTrials(parallelism=search_parallelism)
    
with mlflow.start_run():
        argmin = fmin(
        fn=train,
        space=search_space,
        algo=algo,
        max_evals=8,
        trials=spark_trials)
    
    
    def fit_best_model(X, y): 
        client = mlflow.tracking.MlflowClient()
        experiment_id = client.get_experiment_by_name(experiment_name).experiment_id
    
        runs = mlflow.search_runs(experiment_id)
        best_loss = runs['metrics.loss'].min()
        best_run=runs[runs['metrics.loss'] == best_loss]
    
        best_params = {}
        best_params['gamma'] = float(best_run['params.gamma'])
        best_params['learning_rate'] = float(best_run['params.learning_rate'])
        best_params['max_depth'] = float(best_run['params.max_depth'])
        best_params['min_child_weight'] = float(best_run['params.min_child_weight'])  
        best_params['n_estimators'] = float(best_run['params.n_estimators'])
        
        xgb_regressor =  XGBRegressor(learning_rate=best_params['learning_rate'],
                                max_depth=int(best_params['max_depth']),
                                n_estimators=int(best_params['n_estimators']),
                                gamma=int(best_params['gamma']),
                                min_child_weight = best_params['min_child_weight'], objective='reg:squarederror')
    
        xgb_model = xgb_regressor.fit(X, y, verbose=False)
    
        return(xgb_model)
    
    # fit model using best parameters and log the model
    xgb_model = fit_best_model(X_train, y_train) 
    mlflow.xgboost.log_model(xgb_model, "xgboost") # log the model here 
    
    
    from sklearn.metrics import r2_score
    from sklearn.metrics import mean_squared_error
    train_pred = xgb_model.predict(X_train)
    test_pred = xgb_model.predict(X_test)

IndentationError: unindent does not match any outer indentation level (<tokenize>, line 21)